name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # WAJIB: Install Dependencies
      - name: Install Dependencies
        run: npm install
        working-directory: .  # <-- PERBAIKAN: Memastikan perintah npm berjalan di root

      # WAJIB: Run Linter (Cek Kualitas Kode)
      - name: Run Linter (ESLint)
        run: npm run lint
        working-directory: .  # <-- PERBAIKAN: Memastikan linter berjalan di root

      # WAJIB: Run Unit Test
      - name: Run Unit Test (Jest)
        run: npm test
        working-directory: .  # <-- PERBAIKAN: Memastikan unit test berjalan di root